# itera's declarative hardware-detection battery (nixos-facter).
#
# Extends the `itera.hardware` namespace (see `core/hardware.nix`) with an opt-in
# facter report. nixos-facter (bundled by `modules/nixos/default.nix`) reads a
# machine-readable `facter.json` — captured once per host with the `nixos-facter`
# CLI — and derives that machine's kernel modules, microcode, and driver choices
# from it, replacing nixos-generate-config's point-in-time `hardware-configuration.nix`.
#
# It layers cleanly on the rest of itera:
#   - facter assumes disko and deliberately does NOT manage `fileSystems`, so
#     `itera.disko` keeps owning the disk layout — no conflict.
#   - facter and `itera.hardware`'s broad curated `availableKernelModules` both
#     feed list options, which concatenate; the curated set stays as the fallback
#     for anything the report doesn't cover.
#
# Opt-IN (default OFF): like `itera.disko.device`, it needs a per-machine artifact
# with no sensible default. Generate one with:
#
#   nix run nixpkgs#nixos-facter -- -o facter.json   # commit it to your flake
#
# then point this at it:  itera.hardware.facter.reportPath = ./facter.json;
{
  config,
  lib,
  ...
}:
let
  inherit (lib.options) mkOption;
  inherit (lib.modules) mkIf;
  inherit (lib.types) nullOr path;

  cfg = config.itera.hardware.facter;
in
{
  options.itera.hardware.facter.reportPath = mkOption {
    type = nullOr path;
    default = null;
    example = lib.literalExpression "./facter.json";
    description = ''
      Path to a `facter.json` hardware report generated by the {command}`nixos-facter`
      CLI. `null` (the default) leaves detection to {option}`itera.hardware`'s
      curated module list. When set, nixos-facter drives hardware configuration
      from the report. Requires {option}`itera.disko` (or your own `fileSystems`)
      for the disk layout — facter does not manage filesystems.
    '';
  };

  config = mkIf (config.itera.enable && cfg.reportPath != null) {
    facter.reportPath = cfg.reportPath;
  };
}
