# itera's declarative hardware-detection battery (nixos-facter).
#
# Extends the `itera.hardware` namespace (see `core/hardware.nix`) with a
# nixos-facter report. nixos-facter (bundled by `modules/nixos/default.nix`) reads
# a machine-readable `facter.json` and derives that machine's kernel modules,
# microcode, and driver choices from it, replacing nixos-generate-config's
# point-in-time `hardware-configuration.nix`.
#
# FULLY AUTOMATIC by default. Unlike a committed-into-the-flake report, itera
# regenerates the report on the target host as part of every rebuild and reads it
# from a fixed host-local path:
#
#   1. `itera rebuild` / `update` / `boot` / `update-boot` run `nixos-facter -o
#      <reportPath>` (as root) before building, then build with `--impure` so the
#      just-written report is read at eval time (see cli/itera.sh). This module
#      publishes the effective settings to {file}`/etc/itera/facter.env` for that
#      wrapper to consume.
#   2. `reportPath` defaults to a persisted host-local path
#      ({file}`/var/lib/itera/facter.json`) — outside the flake, so there is
#      nothing to commit and no git churn.
#   3. An NVIDIA GPU in the report auto-enables {option}`itera.nvidia` (see
#      `autoNvidia`), so an NVIDIA machine gets the driver stack with no config.
#
# It layers cleanly on the rest of itera:
#   - facter assumes disko and deliberately does NOT manage `fileSystems`, so
#     `itera.disko` keeps owning the disk layout — no conflict.
#   - facter and `itera.hardware`'s broad curated `availableKernelModules` both
#     feed list options, which concatenate; the curated set stays as the fallback
#     for anything the report doesn't cover.
#
# Purity: reading an absolute report path needs impure evaluation, which the
# rebuild wrapper supplies with `--impure`. Consumption is guarded on
# {command}`builtins.pathExists`, which returns `false` (never throws) in pure
# evaluation for an absolute path — so a pure `nix flake check`, a fresh install,
# or a plain `nixos-rebuild` simply sees no report and falls back to
# `itera.hardware`'s curated module list. A report committed *inside* the flake
# resolves to a store path that `pathExists` sees even in pure eval, so the
# classic committed-report model keeps reading purely.
#
# Opt-OUT: turn off auto-generation with `autoGenerate = false` (falls back to the
# classic "commit a report and point `reportPath` at it" model — set
# `reportPath = ./facter.json`), or auto-NVIDIA with `autoNvidia = false`.
{
  config,
  lib,
  ...
}:
let
  inherit (lib.options) mkOption;
  inherit (lib.modules) mkIf mkMerge mkDefault;
  inherit (lib.types)
    bool
    nullOr
    either
    path
    str
    ;

  cfg = config.itera.hardware.facter;

  # The parsed report the upstream nixos-facter module exposes (`{}` when no
  # report is wired). Its `hardware.graphics_card` entries carry a numeric PCI
  # `vendor.value`; NVIDIA's is 4318 (0x10de).
  gpus = config.facter.report.hardware.graphics_card or [ ];
  hasNvidiaGpu = builtins.any (c: (c.vendor.value or null) == 4318) gpus;

  reportPathStr = toString cfg.reportPath;
  # A host-local (non-store) absolute path is one we can regenerate and must
  # persist; a report committed inside the flake lives under the store instead.
  reportIsHostLocal =
    cfg.reportPath != null
    && lib.hasPrefix "/" reportPathStr
    && !lib.hasPrefix builtins.storeDir reportPathStr;
in
{
  options.itera.hardware.facter = {
    reportPath = mkOption {
      type = nullOr (either path str);
      default = "/var/lib/itera/facter.json";
      example = lib.literalExpression "./facter.json";
      description = ''
        Path to a `facter.json` hardware report generated by the {command}`nixos-facter`
        CLI. Defaults to a persisted host-local path
        ({file}`/var/lib/itera/facter.json`) that {option}`autoGenerate` keeps
        fresh — nothing to commit. When {option}`autoGenerate` is off, set this to
        a report committed inside your flake (e.g. `./facter.json`) instead, or to
        `null` to leave detection to {option}`itera.hardware`'s curated module
        list. Requires {option}`itera.disko` (or your own `fileSystems`) for the
        disk layout — facter does not manage filesystems.
      '';
    };

    autoGenerate = mkOption {
      type = bool;
      default = true;
      description = ''
        Regenerate the {option}`reportPath` report on the target host before every
        rebuild ({command}`itera rebuild`/`update`/`boot`/`update-boot`) and read
        it with an impure evaluation. On by default so hardware detection stays
        current with zero manual steps. Set to `false` to use a report you manage
        yourself (commit one and point {option}`reportPath` at it) and keep builds
        pure.
      '';
    };

    autoNvidia = mkOption {
      type = bool;
      default = true;
      description = ''
        When the facter report shows an NVIDIA GPU, enable {option}`itera.nvidia`
        automatically (via `mkDefault`, so an explicit {option}`itera.nvidia.enable`
        always wins). Enables only the base NVIDIA stack; PRIME/hybrid-laptop
        graphics stays manual (it needs the PCI bus IDs — run
        {command}`itera facter report` for them). Set to `false` if you prefer the
        nouveau driver.
      '';
    };
  };

  config = mkIf config.itera.enable (mkMerge [
    # --- Consume the report ---------------------------------------------------
    # Always guarded on existence: pure eval sees `false` for an absolute path
    # (graceful fallback to curated modules) and `true` for an in-flake store
    # path (committed reports still read purely); an impure rebuild sees the
    # freshly generated host-local report.
    (mkIf (cfg.reportPath != null && builtins.pathExists cfg.reportPath) {
      facter.reportPath = cfg.reportPath;
    })

    # --- Tell the rebuild wrapper (cli/itera.sh) what to do -------------------
    # Absent file => feature off, so older generations / non-itera systems behave
    # like a plain `nh` call.
    {
      environment.etc."itera/facter.env".text =
        if cfg.autoGenerate && cfg.reportPath != null then
          ''
            ITERA_FACTER_AUTOGEN=1
            ITERA_FACTER_REPORT_PATH=${reportPathStr}
          ''
        else
          ''
            ITERA_FACTER_AUTOGEN=0
          '';
    }

    # --- Persist the auto-generated report across the tmpfs root --------------
    # So it survives reboots and a manual `nh os switch -- --impure` still finds
    # it. Only for a host-local absolute path (a committed report is in the store).
    (mkIf (cfg.autoGenerate && reportIsHostLocal) {
      itera.impermanence.directories = [ (builtins.dirOf reportPathStr) ];
    })

    # --- Auto-enable NVIDIA when the report shows an NVIDIA GPU ---------------
    (mkIf cfg.autoNvidia {
      itera.nvidia.enable = mkDefault hasNvidiaGpu;
    })
  ]);
}
